language: dart
sudo: required

dist: trusty

dart:
 - dev
 - stable

# Content shell needs these fonts.
addons:
  apt:
    packages:
    - ttf-kochi-mincho
    - ttf-kochi-gothic
    - ttf-dejavu
    - ttf-indic-fonts
    - fonts-tlwg-garuda

before_install:
  # Content shell needs this font. Since it has a EULA, we need to manually
  # install it.
  #
  - sudo apt-get update -yq
  - sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
  - sudo apt-get install msttcorefonts -qq

dart_task:
 # Browser tests take particularly long on Dartium, so we split them up into different tasks.
 - test: --platform vm

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache