language: dart
sudo: required

dist: trusty

dart:
 - stable

  - chmod ugo+x tool/travis.sh

script: ./tool/travis.sh

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache