name: angular_utility
version: 0.0.4

environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  glob: ^1.1.3
  package_resolver: ^1.0.2
  source_span: ^1.4.0
  grinder: 0.8.0+3
  sass_builder: ^0.1.1
  build_runner: 0.3.4
dev_dependencies:
  test: 0.12.24