name: angular_utility
version: 0.0.2
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  glob: ^1.1.3
  package_resolver: ^1.0.2
  source_span: ^1.4.0
  grinder:
dev_dependencies:
  test: 0.12.24
  angular_components: 0.5.3