name: angular_utility
version: 0.1.0-alpha

environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  glob: ^1.1.3
  package_resolver: ^1.0.2
  source_span: ^1.4.0
  grinder: 0.8.0+3
  sass_builder: ^1.0.1
  build_runner:
dev_dependencies:
  test: 0.12.24