name: angular_utility
version: 0.1.0-alpha+5

environment:
  sdk: 1.24.3
dependencies:
  glob: ^1.1.3
  package_resolver: ^1.0.2
  source_span: ^1.4.0
  sass_builder: ^1.1.1
  build_runner: 0.6.0
dev_dependencies:
  test: ^0.12.24
dependency_overrides:
  build_runner: 0.6.0